name: build docker and publish

on:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build tag
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64, linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mitre-attack-navigator:latest
          file: Dockerfile
